name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6.1.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v6.0.0
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore

      - name: Build Docker image
        run: |
          docker build -t ticketreservationsystem:latest .

      - name: Save Docker image
        run: |
          docker save ticketreservationsystem:latest | gzip > ticketreservationsystem.tar.gz

      - name: Copy image to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 11210
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "ticketreservationsystem.tar.gz"
          target: "/tmp"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 11210
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker load < /tmp/ticketreservationsystem.tar.gz

            cd opt/TicketReservationSystem

            docker compose up -d --force-recreate --remove-orphans

            rm /tmp/ticketreservationsystem.tar.gz

            docker image prune -f
